### PR TITLE
Show module import error traceback

### LINKED ISSUE #121: More informative errors / traceback?
There's probably an easy way to do this but I couldn't find it from looking at the docs. 

Say that my yaml file points to an external likelihood in a module in the same directory. I then insert a syntax error into the module that would prevent it from even being imported. I run the cobaya wrapper

```
$ cobaya-run act.yml --debug
..... LOTS OF MESSAGES....
 2020-10-27 12:51:16,296 [numba.core.ssa] ================================================================================
 2020-10-27 12:51:17,551 [tools] *ERROR* There was a problem when importing likelihood 'act_pylike.act100':
 2020-10-27 12:51:17,551 [input] *ERROR* Failed to get defaults for component or class 'act_pylike.act100' [No module named 'cobaya.likelihoods.act_pylike']
```

Ok, this tells me there was *some* error. But it doesn't tell me whether it was a silly missing parantheses, or some file the likelihood couldn't find or something else. Any source of error will give me the same message above. How/why does cobaya throw out the traceback for errors? Would it be possible to always print the full traceback?

I'm on the master branch and up-to-date, though I've seen this problem back in January too.

### PR DESCRIPTION
**Pull request by msyriac**
This fixes #121 .

### CODE REVIEW

**Comment by JesusTorrado** [comment]
Hi @msyriac 

Thanks for the PR!

I think the traceback is printed a little too early. Looking into it right now.

Could you please copy here what the traceback prints in your example?

**Comment by cmbant** [comment]
Thanks. Interesting, Yesterday I tried adding 

`log.error("".join(list(traceback.format_exception(*exc_info))))`

before log.error("there was a problem..") just a bit further down, but I thought I didn't get the actual error message. But today I tried it again and I do... so if it works it may be better, as it uses the logging system and avoids repeating the message for actual module not found errors.

**Comment by JesusTorrado** [comment]
@cmbant works for me. Maybe just before the "There was a problem when importing..." `log.error`?

**Comment by msyriac** [comment]
If you mean around Line 145 in tools.py, that doesn't work for me. Here is what I get when I put Antony's suggestion right before that log.error:

```
$ cobaya-run act.yml 
[output_mpi] Output to be read-from/written-into folder 'chains', with prefix 'bandpass_run_test'
[tools] *ERROR* Traceback (most recent call last):
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/cobaya/cobaya/tools.py", line 215, in get_class
    return return_class(internal_module_name, package=_cobaya_package)
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/cobaya/cobaya/tools.py", line 195, in return_class
    _module = load_module(_module_name, package=package, path=component_path)
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/cobaya/cobaya/tools.py", line 158, in load_module
    component = import_module(name, package=package)
  File "/scinet/niagara/intel/2018.2/intelpython3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cobaya.likelihoods.act_pylike'

[tools] *ERROR* There was a problem when importing likelihood 'act_pylike.act100':
[input] *ERROR* Failed to get defaults for component or class 'act_pylike.act100' [No module named 'cobaya.likelihoods.act_pylike']
```

With my original suggestion, I get:
```
$ cobaya-run act.yml 
[output_mpi] Output to be read-from/written-into folder 'chains', with prefix 'bandpass_run_test'
Traceback (most recent call last):
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/cobaya/cobaya/tools.py", line 215, in get_class
    return return_class(internal_module_name, package=_cobaya_package)
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/cobaya/cobaya/tools.py", line 195, in return_class
    _module = load_module(_module_name, package=package, path=component_path)
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/cobaya/cobaya/tools.py", line 158, in load_module
    component = import_module(name, package=package)
  File "/scinet/niagara/intel/2018.2/intelpython3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cobaya.likelihoods.act_pylike'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/cobaya/cobaya/tools.py", line 222, in get_class
    import_module(module_name)
  File "/scinet/niagara/intel/2018.2/intelpython3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/bplike/act_pylike.py", line 11, in <module>
    kljasd8;ASD
NameError: name 'kljasd8' is not defined
[tools] *ERROR* There was a problem when importing likelihood 'act_pylike.act100':
[input] *ERROR* Failed to get defaults for component or class 'act_pylike.act100' [No module named 'cobaya.likelihoods.act_pylike']
```

which picks up the original problem, which is that I added some undefined garbage `kljasd8` to the external likelihood module `act_pylike`.

**Comment by JesusTorrado** [comment]
Do you mean 245 instead of 145?

**Comment by msyriac** [comment]
Right, yes, Line 245!

**Comment by JesusTorrado** [comment]
Maybe we can save the traceback (easier when already casted into string) and print it in 245?

**Comment by msyriac** [comment]
Yes, I think that can work. In fact, we don't need the `traceback` module, we could just replace `traceback.print_exc()` with
`exc_info = sys.exc_info()`.

**Comment by msyriac** [comment]
This will leave the printing to the logger. Antony's suggestion would show the full traceback, but even without it, the error message becomes more informative:

```
$ cobaya-run act.yml 
[output_mpi] Output to be read-from/written-into folder 'chains', with prefix 'bandpass_run_test'
[tools] *ERROR* There was a problem when importing likelihood 'act_pylike.act100':
[input] *ERROR* Failed to get defaults for component or class 'act_pylike.act100' [name 'kljasd8' is not defined]
```

**Comment by msyriac** [comment]
Let me know which you prefer and I'll update the PR.

**Comment by JesusTorrado** [comment]
To me, the rationale it "don't print the traceback if you know exactly what failed, but do it you don't", so I'd say yes to traceback in this case before line 244 (242 before the PR).

@cmbant ?

**Comment by msyriac** [comment]
Ok, I've updated the PR.

**Comment by cmbant** [comment]
Thanks, looks good to me

**Pull request merged**
