### PR TITLE
component: allows inheriting component (to have 2 of same class)

### PR DESCRIPTION
**Pull request by JesusTorrado**
Basic implementation for #126. Allows things like:

    likelihood:
      mybao1:
        inherits: bao.generic
        [options]
      mybao2:
        inherits: bao.generic
        [options]

@Pablo-Lemos could you see if this works for you, and poke it a bit to see if you find some unexpected error?

TODO:
- [ ] to-do's in code.

### CODE REVIEW

**Comment by Pablo-Lemos** [comment]
Just tried it and it works perfectly, really helpful, thanks!

**Comment by JesusTorrado** [comment]
Hi @Pablo-Lemos 

This is almost ready to merge. Notice that I have replaced `inherits` by `class`, since this is not actually inheritance, but multiple instantiation of the same class.

**Comment by Pablo-Lemos** [comment]
I saw that this stopped working on the latest version, is there an easy fix? Thanks!

**Comment by JesusTorrado** [comment]
It's apparently working on my side. Are you sure you are using `class` instead of `inherits`? Can you post a minimal script to reproduce it?

**Comment by Pablo-Lemos** [comment]
No, I was not. It works now, thanks!

**Pull request merged**
