### PR TITLE
add sigma_R to classy (WIP)

### PR DESCRIPTION
**Pull request by timothydmorton**
Wanted to open this to get feedback; haven't checked if this matches the expected format of `sigma_R` from CAMB.  I also tried to mimic how this was done on the CAMB side, and I don't understand much of it, but this does seem to successfully give back the sigma computed by classy.  Let me know if you have suggestions!

### CODE REVIEW

**Comment by cmbant** [comment]
Would be nice to add unit test analogue of test_CAMB_sigma_R to check it works with the same syntax (and gives same result!)

**Comment by timothydmorton** [comment]
Agreed!  Will do so at my earliest convenience.

**Comment by cmbant** [comment]
@timothydmorton ping for test?

**Comment by JesusTorrado** [comment]
Done in https://github.com/CobayaSampler/cobaya/pull/222, with a slightly different syntax (using `arg_array` to get parameter combinations).

**Pull request closed without merging**
