### PR TITLE
More general input derived parameter dependencies

### PR DESCRIPTION
**Pull request by cmbant**
Currently things like
```

  xx: 
    value: 12
    drop: True
  xy:
    value: "lambda xx: xx*2"
    drop: True
  x:
    value: "lambda xy, xx: xx*xy"  
```
generate an error that "xy" is not used by any likelihood (assuming it isn't). Ideally we'd support nested dependencies, but I think currently not supported, so  this pull just changes the way the existing nested dependency error is raised. Not sure if that error is supposed to be catching other cases not captured by this.

### CODE REVIEW

**Comment by cmbant** [comment]
Now trying to make nested lambda dependencies like the example above just work

**Comment by cmbant** [comment]
@JesusTorrado, do I recall correctly that drop is now always redundant as long as not using any agnostic theory - i.e. I guess only needed when used with Class, or does it have other uses?

**Comment by cmbant** [comment]
Notes: parameterization._derived_dependencies is currently not used

@Pablo-Lemos I think this should fix the issue you had trying to use omegab as an input parameter, if you have a chance to test it let me know if it still doesn't work

**Comment by JesusTorrado** [comment]
> @JesusTorrado, do I recall correctly that drop is now always redundant as long as not using any agnostic theory - i.e. I guess only needed when used with Class, or does it have other uses?

You may want to give a name to a parameter that coincides with one understood by e.g. CAMB (maybe accidentally: CAMB understands so many parameters that you may not know that your defined one shares a name with a CAMB one, and you'd get a strange error in that case if you don't use `drop`).

**Comment by cmbant** [comment]
OK thanks. I've re-jigged this a bit, so dropped parameters are now included in input_params, and only explicitly removed when assigning to theory/likelihoods (so priors can now depend on dropped and undropped input and derived parameters, and simplifying a few things).

**Pull request merged**
