### PR TITLE
Bao

### PR DESCRIPTION
**Pull request by Pablo-Lemos**
Just adds the Hubble distance as a BAO measurement, as in eq. (14) of https://arxiv.org/pdf/2007.08991.pdf

### CODE REVIEW

**Comment by cmbant** [comment]
Weird, not sure why the PR file diff (https://github.com/CobayaSampler/cobaya/pull/122/files) is showing generic.py also changed (perhaps because a repeated pull branch?) Anyway looks fine.

What goes wrong with invcov?

**Comment by Pablo-Lemos** [comment]
The strange thing is that it seems that in the repo it is currently named generic instead of bao_generic. 

The error with invcov (I do not understand why it happens): 

"likelihood 'bao.generic' does not recognize some options: 'invcov_file' (did you mean 'cov_file'|'measurements_file'?). Check the documentation for 'likelihood'."

**Comment by cmbant** [comment]
Try adding invcov_file to generic.yaml?

**Comment by Pablo-Lemos** [comment]
Same problem I am afraid

**Comment by JesusTorrado** [comment]
Hi @Pablo-Lemos 

I have just checked explicitly that adding `invcov_file` to `generic.yaml` makes it work in your branch. Maybe you forgot to re-install after checking-out (of you are not using `pip -e`)?

**Comment by Pablo-Lemos** [comment]
You're right @JesusTorrado, pushed now!

**Comment by JesusTorrado** [comment]
Great! I'll merge and add a unit test for `bao.generic`

**Pull request merged**
