### PR TITLE
Corrected extra factor 2

### PR DESCRIPTION
**Pull request by Pablo-Lemos**
Thanks @seshnadathur for pointing it out!

### CODE REVIEW

**Comment by cmbant** [comment]
Did you forget to update the unit test?

**Comment by cmbant** [comment]
Thanks!

**Comment by seshnadathur** [comment]
A possibly silly question: now this has been merged to main, if I do `python -m pip install cobaya --upgrade` on my cluster now (I do need to do this again as it as somehow been uninstalled), I will be running the version with the corrected factor of 2, right? Just unsure because the version number is still 3.2.1.

**Comment by cmbant** [comment]
No, you'd need to wait for another release for it to appear on pip - easiest probably just to do a "pip install -e" from the git source

**Comment by seshnadathur** [comment]
Thanks

**Pull request merged**
