### PR TITLE
Simple implementation for vector parameters

### PR DESCRIPTION
**Pull request by JesusTorrado**

### CODE REVIEW

**Comment by JesusTorrado** [comment]
@cmbant do you want to take a look before merge? Should be done.

It's just documentation and better error control.

Only actual change needed is in getdist (see https://github.com/cmbant/getdist/pull/68)

Minimal working example:

    from scipy import stats


    def gauss_band(x_vector):
        return stats.norm.logpdf(
            x_vector[0] + x_vector[1], loc=1, scale=0.02)

    # NB: don't forget the 'drop: True' in the individual parameters
    #     and 'derived: False' in the vector parameters

    info = {
        "likelihood": {"band": gauss_band},
        "params": {
            "x": {"prior": {"min": 0, "max": 2}, "proposal": 0.1, "drop": True},
            "y": {"prior": {"min": 0, "max": 2}, "proposal": 0.1, "drop": True},
            "x_vector": {"value": lambda x, y: [x, y], "derived": False}},
        "sampler": {"mcmc": None}}

    info["force"] = True
    info["output"] = "chains/band"

    from cobaya.run import run
    updated_info, sampler = run(info)

**Comment by cmbant** [comment]
Interesting that just works, looks OK to me though have not tested.

**Comment by JesusTorrado** [comment]
Yeah, surprisingly easy. I vaguely remember seeing this applied to some weird "vector is string form" of CLASS by @nataliehogg in some issue that I cannot find at the moment (so @nataliehogg, if you see this and can confirm, I am happy to give you credit in the changelog).

As for mergning, I would wait until the next GetDist release, since it's a requirement.

**Comment by lukashergt** [comment]
> Yeah, surprisingly easy.

To a big part that is down to the nice flexible input setup of Cobaya. Glad [#110](https://github.com/CobayaSampler/cobaya/issues/110#issuecomment-652333489) proved helpful.

**Pull request closed without merging**
